const USER = 'mrsmartass700-blip';
const WORDS = ['PYTHON','AI','CODE','LUA','C++'];
const $ = s => document.querySelector(s);
let w = 0;
setInterval(()=>{ const el=$('#word'); el.animate([{opacity:1,transform:'translateY(0)'},{opacity:0,transform:'translateY(-18px)'}],{duration:180,fill:'forwards'}).onfinish=()=>{el.textContent=WORDS[++w%WORDS.length];el.animate([{opacity:0,transform:'translateY(18px)'},{opacity:1,transform:'translateY(0)'}],{duration:300,fill:'forwards'});};},1800);
const skills=['AI SYSTEMS','PYTHON','LUA','AUTOMATION','BOTS','GIT + GITHUB','DEEPSEEK','CHROME','TELEGRAM','DISCORD','VR / XR','STEAM','EPIC GAMES','MODDING','FL STUDIO','WINDOWS','LINUX','macOS','iOS / ANDROID','BIOS / HARDWARE'];
$('#skillsList').innerHTML=skills.map((x,i)=>`<div class="skill" style="transition-delay:${i*35}ms"><span>${String(i+1).padStart(2,'0')} · ${x}</span><b>OK</b></div>`).join('');
function reposSkeleton(){return Array.from({length:5},(_,i)=>`<a class="repo" href="https://github.com/${USER}?tab=repositories" target="_blank"><span class="repo-name">OPEN SLOT 0${i+1}</span><span class="repo-info"><span class="lang">GITHUB</span><span>↗</span></span></a>`).join('')}
async function getRepos(){const root=$('#repos');root.innerHTML=reposSkeleton();try{let r=await fetch(`https://api.github.com/users/${USER}/repos?sort=updated&per_page=100`);if(!r.ok)throw Error();let data=await r.json();data=data.filter(x=>!x.fork&&x.name.toLowerCase()!==`${USER}.github.io`.toLowerCase()).slice(0,5);root.innerHTML=data.length?data.map(x=>`<a class="repo" href="${x.html_url}" target="_blank" rel="noreferrer"><span class="repo-name">${x.name}</span><span class="repo-info"><span class="lang">${x.language||'CODE'}</span><span>★ ${x.stargazers_count||0} ↗</span></span></a>`).join(''):reposSkeleton()}catch(e){console.warn('GitHub API unavailable',e)}}getRepos();
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('show');observer.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('.reveal,.receipt').forEach(x=>observer.observe(x));
$('#themeToggle').onclick=()=>{document.documentElement.classList.toggle('light');localStorage.setItem('ms-theme',document.documentElement.classList.contains('light')?'light':'dark')};if(localStorage.getItem('ms-theme')==='light')document.documentElement.classList.add('light');
const c=$('#grain'),ctx=c.getContext('2d');function noise(){c.width=innerWidth/3;c.height=innerHeight/3;let d=ctx.createImageData(c.width,c.height);for(let i=0;i<d.data.length;i+=4){let v=Math.random()*255;d.data[i]=d.data[i+1]=d.data[i+2]=v;d.data[i+3]=20}ctx.putImageData(d,0,0)}noise();setInterval(noise,220);
